name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
    - uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
    - name: Install Dependencies
      run: poetry install
    - name: build the sucker
      run: make build
      # https://stackoverflow.com/a/64195658
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "utils"
        body: "It's releasin' time"
        generateReleaseNotes: true
        tag: ${SHORT_SHA}
        commit: master
        token: ${{ secrets.PAT }}
